version: "3"
services:
  imagick_php_backend:
    build: docker/php_backend
    image: imagick_php_backend:latest
    volumes:
      - .:/var/www
      - ../clavis.php:/var/clavis.php
    restart: always
  imagick_php_backend_debug:
    build: docker/php_backend_debug
    image: imagick_php_backend_debug:latest
    volumes:
      - .:/var/www
    restart: always
  redis:
    image: redis:4.0.6
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  web_server:
    build: docker/web_server
    image: imagick_web_server:latest
    command: ["/usr/sbin/nginx", "-c", "/etc/config/nginx.conf"]
    depends_on:
      - imagick_php_backend
      - imagick_php_backend_debug
    volumes:
      - .:/var/www
      - ./docker/web_server/config:/etc/config
    ports:
      - "80:8000"
    restart: always
  workers:
    build: docker/worker
    image: imagick_php_worker:latest
    depends_on:
     - redis
    volumes:
      - .:/var/www
      - ../clavis.php:/var/clavis.php
    restart: always